# Generated by Django 3.2.6 on 2021-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.JSONField()),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date of purchase')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
